### ISSUE TITLE
Sigma_w from Sigma_iw

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/maxent#6] opened 2019-02-28 21:05 UTC
Dear All
Hi
After a DFT+DMFT calculation, I want to conversion Sigma_iw to Sigma_w using max-entropy.
For doing it, I run "sigma_continuator_SRO_1 and 2" from maxant site for SrVO3 compound. 
But when I run "sigma_continuator_SRO_2.py" for this compound but I have the below error:
"AttributeError:'InversionSigmaContinuator object has no attribute 'Sigma_w' 
Can you please help me how I can conversion "Sigma_iw" from "case.h5" file to "Sigma_w" and save it in to this file?
Thank you ery much for any help to me
Reyhaneh

**Comment by gkraberger** [comment] 2019-03-04 17:58
Hi Reyhaneh,

Thanks for contributing this issue.

I get a different error, 

```
Traceback (most recent call last):
  File "sigma_continuator_SRO_2.py", line 9, in <module>
    for key in S_iw.indices:
NameError: name 'S_iw' is not defined
```

When I fix this (see diff below), I run into (more or less) the error you mentioned.

```
--- a/doc/guide/sro/sigma_continuator_SRO_2.py
+++ b/doc/guide/sro/sigma_continuator_SRO_2.py
@@ -6,6 +6,7 @@ from pytriqs.plot.mpl_interface import oplot
 # load res and SigmaContinuator from h5-file
 res = {}
 with HDFArchive('Sr2RuO4_b37.h5', 'r') as ar:
+    S_iw = ar['S_iw']
     for key in S_iw.indices:
         res[key] = ar['maxent_result_' + key]
     isc = ar['isc']
```

The error:

```
Traceback (most recent call last):
  File "sigma_continuator_SRO_2.py", line 34, in <module>
    oplot(isc.S_w['up_0'], mode='I', label='maxent xy', lw=3)
AttributeError: 'InversionSigmaContinuator' object has no attribute 'S_w'
```

(the difference between your and my error message is that mine states `S_w` instead of `Sigma_w`).

When I change

```
 # save SigmaContinuator again (now it contains S_w)
 with HDFArchive('Sr2RuO4_b37.h5', 'a') as ar:
-    isc = ar['isc']
+     ar['isc'] = isc
```

it works. Also, the comment above the with clause seems to indicate that we indeed want to save and not read the h5.

@mzingl, the SigmaContinuator is your work, can you please confirm that this is doing what it is intended to do when implementing my diffs and then commit this? Thanks!

@Reyhanehe I hope that Manuel will fix this soon, then you can use the fixed version and it should work. Be careful - the block names are hard-coded in the file, maybe you have to adapt them for SVO.

Best
Gernot

**Comment by Reyhanehe** [comment] 2019-03-05 10:34
Dear Gkraberger 
Hi
This problrm was solved when I used Sigma_iw in h5 file for SrVO3 instead of S_w.
also For SrRuO4 compound the solution that you sent is work and run is done.
now the sigma_w that is saved in isc?and I should using it from this place?
Thanks so much

**Comment by mzingl** [comment] 2019-03-05 14:17
Should be fixed now.

**Closed by mzingl** 2019-03-05 14:17 UTC

**Comment by cmtcl18** [comment] 2019-10-19 18:22
Dear Developers,
The issue is similar to this issue( Conver
ting Sigma_w from Sigma_iw ), so I did not open new issue. 
I successfully run the analytic continuation for self-energy using MAXENT. I want to get the real frequency self energy, for calculating the  DOS  the band structure. For this purpose, I run the following command 

res = {}
with HDFArchive('SrVO3.h5', 'r') as ar:
    Sigma_iw = ar['dmft_output']['Sigma_iw']
    for key in Sigma_iw.indices:
        res[key] = ar['maxent_result_' + key]

    isc = ar['isc']

But, I am getting the following error

Traceback (most recent call last):
  File "DOS.py", line 14, in <module>
    res[key] = ar['maxent_result_' + key]
  File "/home/jatin/triqs/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 228, in __getitem__
    return self.__getitem1__(key,self._reconstruct_python_objects)
  File "/home/jatin/triqs/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 235, in __getitem1__
    if key not in self  : raise KeyError, "Key %s does not exist."%key
KeyError: 'Key maxent_result_up_2 does not exist.'

Can anyone help to resolve the issue?
I will be thankful for your suggestion

Best Regards,
CMTCL

**Comment by the-hampel** [comment] 2019-10-19 21:23
Hi CMTCL,
It appears that the object with key "maxent_result_up_2 " does simply not exist in your h5 archive. Try first to look in the h5 archive structure with `print a5` and consider the output. You are asking python to load the key "maxent_result_up_2", which probably does not exist. So you need to check how you saved your maxent results to the h5 archive and the load them with the proper name.

Best,
Alex

**Comment by cmtcl18** [comment] 2019-10-28 18:12
Dear All,
For converting Sigma_iw to Sigma_w I want to use the following command.
# get S_w from the auxilliary spectral function Aaux_w
Aaux_w = {}
w = res['up_0'].omega
for key in res:
    Aaux_w[key] = res[key].analyzer_results['LineFitAnalyzer']['A_out']

isc.set_Gaux_w_from_Aaux_w(Aaux_w, w, np_interp_A=10000,
                           np_omega=4000, w_min=-1.0, w_max=1.0)

# save SigmaContinuator again (now it contains S_w)
with HDFArchive('SrVO3_maxent.h5', 'a') as ar:
    ar['isc'] = isc
The above command is from the Continuation of of self-energies: Sr2RuO4

Using this, I am getting the following error.

Traceback (most recent call last):
  File "maxent.py", line 71, in <module>
    Aaux_w[key] = res[key]['analyzer_results']['LineFitAnalyzer']['A_out']
  File "/home/jatin/triqs/install/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 275, in __getitem__
    assert isinstance(key, (MeshPoint, Idx))
AssertionError

Can any one help to sort-out the error?
I will be helpful for your suggestion.

Best Regards,
CMTCL
